### ISSUE TITLE
🚀 feat(env): Ability to specify kind cluster configuration

### ISSUE THREAD

**Issue by finlaysawyer** [web-seven/overlock#280]
### 🔖 Feature description

When setting up kind, you can provide configuration to configure a registry mirror for images. It would be great if this was supported in overlock too.

```yaml
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
containerdConfigPatches:
- |-
  [plugins."io.containerd.grpc.v1.cri".registry.mirrors."docker.io"]
    endpoint = ["https://my-custom-registry:5000"]
```

### 🎤 Context

The `registry:2` image used for the overlock registry is pulled from `docker.io`. However, the setup often fails in CI pipelines due to rate limits from DockerHub across shared IP addresses. Being able to configure an internal mirror would prevent this.

### ✌️ Possible Implementation

We can enhance `overlock environment create` to support passing a [configuration file](https://kind.sigs.k8s.io/docs/user/configuration/).

### 👀 Have you spent some time to check if this feature request has been raised before?

- [x] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [x] I have read the [Code of Conduct](https://github.com/web-seven/overlock/blob/main/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

If this feature is accepted, sure.
